name: Docker CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build artifact
      run: |
        mkdir build
        cp app.js build/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: build/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-build
        path: build/

    - name: Build Docker Image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/devops-demo .

    - name: Push Image
      run: docker push ${{secrets.DOCKER_USERNAME}}/devops-demo